### ISSUE TITLE
Please rename the project

### ISSUE THREAD

**Issue by ku1ik** [gvcgo/asciinema#2]
Hi!

Given this project is an unofficial re-implementation of the [asciinema CLI](https://github.com/asciinema/asciinema) I kindly ask you to rename this project. I'm happy about alternative asciicast recorder implementations, but having this repo and the binary named "asciinema" may give an impression that this is the official, original one, which it is not. Also, I'd appreciate if you removed the asciinema.org link from the repo's About sidebar. Again, this gives an impression that asciinema.org is a homepage for your project, which it is not. I don't mind links to asciinema.org from your README, as long as it's clear that link refers to the asciinema project, not your re-implementation.

Thanks!

**Comment by moqsien** [comment]
Thanks for your friendly reminder. The link from the About sidebar has been removed. And I'll rename this repo later.

**Comment by ku1ik** [comment]
Appreciate that, thank you.

**Comment by ku1ik** [comment]
Btw, just curious, was the lack of Windows support the main motivation for this project?

I plan to look into Windows support after releasing 3.0, as I heard ConPTY is pretty good, but won't promise anything 😅

**Comment by moqsien** [comment]
> Btw, just curious, was the lack of Windows support the main motivation for this project?
> 
> I plan to look into Windows support after releasing 3.0, as I heard ConPTY is pretty good, but won't promise anything 😅

Not only the lack of Windows support, but also the support to edit .cast files.

I've just renamed the Repo Name in Readme Card, so it can not create a misleading impression now. 

https://github.com/moqsien/moqsien
